# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  lint:
    strategy:
      matrix:
        go: [ stable ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12

  test:
    strategy:
      matrix:
        go: [ stable ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test with coverage
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Test
      if: ${{ matrix.os != 'ubuntu-latest' }}
      run: go test -race ./...

    - name: Coverage
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: go tool cover -func=coverage.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      if: ${{ matrix.os == 'ubuntu-latest' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
